config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/index'

  resources :blogs

   root 'pages#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
	resourcify
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :post, :author)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %><br />
  </div>
  <div class="field">
    <%= f.label :post %><br>
    <%= f.cktext_area :post %><br />
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %><br />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<head>
    <!-- this styles only adds some repairs on idevices  -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Google fonts - witch you want to use - (rest you can just remove) -->
    <link href='http://fonts.googleapis.com/css?family=Montserrat+Alternates:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    
    <!--[if elt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
    
    <!-- ######### CSS STYLES ######### -->
  
    <link rel="stylesheet" href="css/reset.css" type="text/css" />
  <link rel="stylesheet" href="css/style.css" type="text/css" />
    
    <link rel="stylesheet" href="css/font-awesome/css/font-awesome.min.css">
    
    <!-- responsive devices styles -->
  <link rel="stylesheet" media="screen" href="css/responsive-leyouts.css" type="text/css" />
    
<!-- just remove the below comments witch color skin you want to use -->
    <!-- <link rel="stylesheet" href="css/colors/red.css" /> -->
    <!--<link rel="stylesheet" href="css/colors/green.css" />-->
    <!--<link rel="stylesheet" href="css/colors/cyan.css" />-->
    <link rel="stylesheet" href="css/colors/orange.css" /> 
   <!-- <link rel="stylesheet" href="css/colors/lightblue.css" /> -->
    <!--<link rel="stylesheet" href="css/colors/pink.css" />-->
    <!--<link rel="stylesheet" href="css/colors/purple.css" />-->
    <!--<link rel="stylesheet" href="css/colors/bridge.css" />-->
   <!-- <link rel="stylesheet" href="css/colors/slate.css" /> -->
    <!--<link rel="stylesheet" href="css/colors/yellow.css" />-->
    <!-- <link rel="stylesheet" href="css/colors/darkred.css" /> -->
  
  
    <!-- menu -->
    <link href="js/mainmenu/sticky.css" rel="stylesheet">
    <link rel="stylesheet" href="js/mainmenu/menu.css">
    <!-- forms -->
    <link rel="stylesheet" href="js/form/sky-forms.css" type="text/css" media="all">
    
    
</head>



<div class="site_wrapper">

<div id="header">
    
  <div id="trueHeader">
    
  <div class="wrapper">
    
     <div class="container_full">
        
        <header>
        
            <!-- Logo -->
            <div class="logo"><a href="/#home"><img src="images/logo_horz_black_back.jpg" alt="Nuvola Networks Logo" /></a></div>
            
            <!-- Menu -->
            <div class="menu_main">
            
            <nav class="nav-collapse">
                <ul>
                  <li><a href="/#home">Home</a></li>
                  <li><a href="/#about">About</a></li>
               <!--   <li><a href="#portfolio" data-scroll><i class="fa fa-circle"></i>Portfolio</a></li> -->
                  <li><a href="/#services">Services</a></li>
                  <li><a href="/#pricing">Pricing</a></li>
                  <li><a href="/#blog">Blog</a></li>
                  <li><a href="/#contact">Contact</a></li>
                </ul>
            </nav>
            
            </div><!-- end menu -->  
        
        </header>
        
     </div>
    
  </div>
    
  </div>
    
</div>
<div class="clearfix"></div>

<div class="container">
    <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>
<% else %>

<h1>You are not Authorized to be here! <a href="http://www.nuvola-networks.com"> Go Back</a></h1>
<% end %>
<% end %>
</div>

<div class="clearfix"></div>

<div class="copyrights">
<div class="container">
  
    <ul>
        <li><a href="http://www.facebook.com/nuvolanetworks"><i class="fa fa-facebook"></i></a></li>
        <li><a href="http://www.twitter.com/nuvolanetworks"><i class="fa fa-twitter"></i></a></li>
        <li><a href="https://plus.google.com/+RickBarkley1"><i class="fa fa-google-plus"></i></a></li>
        <li><a href="http://pintrest.com/nuvolio"><i class="fa fa-pinterest"></i></a></li>
        <li><a href="https://www.linkedin.com/company/nuvola-networks-llc"><i class="fa fa-linkedin"></i></a></li>
    </ul>
    
    <div class="clearfix"></div>
    <div class="margin_top3"></div>
    
    © Nuvola Networks. All rights reserved.

</div>
</div><!-- end copyrights section -->

<a href="#" class="scrollup">Scroll</a><!-- end scroll to top of the page-->

</div>

app/views/blogs/index.html.erb
<head>
    <!-- this styles only adds some repairs on idevices  -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Google fonts - witch you want to use - (rest you can just remove) -->
    <link href='http://fonts.googleapis.com/css?family=Montserrat+Alternates:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    
    <!--[if elt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
    
    <!-- ######### CSS STYLES ######### -->
  
    <link rel="stylesheet" href="css/reset.css" type="text/css" />
  <link rel="stylesheet" href="css/style.css" type="text/css" />
    
    <link rel="stylesheet" href="css/font-awesome/css/font-awesome.min.css">
    
    <!-- responsive devices styles -->
  <link rel="stylesheet" media="screen" href="css/responsive-leyouts.css" type="text/css" />
    
<!-- just remove the below comments witch color skin you want to use -->
    <!-- <link rel="stylesheet" href="css/colors/red.css" /> -->
    <!--<link rel="stylesheet" href="css/colors/green.css" />-->
    <!--<link rel="stylesheet" href="css/colors/cyan.css" />-->
    <link rel="stylesheet" href="css/colors/orange.css" /> 
   <!-- <link rel="stylesheet" href="css/colors/lightblue.css" /> -->
    <!--<link rel="stylesheet" href="css/colors/pink.css" />-->
    <!--<link rel="stylesheet" href="css/colors/purple.css" />-->
    <!--<link rel="stylesheet" href="css/colors/bridge.css" />-->
   <!-- <link rel="stylesheet" href="css/colors/slate.css" /> -->
    <!--<link rel="stylesheet" href="css/colors/yellow.css" />-->
    <!-- <link rel="stylesheet" href="css/colors/darkred.css" /> -->
  
  
    <!-- menu -->
    <link href="js/mainmenu/sticky.css" rel="stylesheet">
    <link rel="stylesheet" href="js/mainmenu/menu.css">
    <!-- forms -->
    <link rel="stylesheet" href="js/form/sky-forms.css" type="text/css" media="all">
    
    
</head>



<div class="site_wrapper">

<div id="header">
    
  <div id="trueHeader">
    
  <div class="wrapper">
    
     <div class="container_full">
        
        <header>
        
            <!-- Logo -->
            <div class="logo"><a href="/#home"><img src="images/logo_horz_black_back.jpg" alt="Nuvola Networks Logo" /></a></div>
            
            <!-- Menu -->
            <div class="menu_main">
            
            <nav class="nav-collapse">
                <ul>
                  <li><a href="/#home">Home</a></li>
                  <li><a href="/#about">About</a></li>
               <!--   <li><a href="#portfolio" data-scroll><i class="fa fa-circle"></i>Portfolio</a></li> -->
                  <li><a href="/#services">Services</a></li>
                  <li><a href="/#pricing">Pricing</a></li>
                  <li><a href="/#blog">Blog</a></li>
                  <li><a href="/#contact">Contact</a></li>
                </ul>
            </nav>
            
            </div><!-- end menu -->  
        
        </header>
        
     </div>
    
  </div>
    
  </div>
    
</div>

<div class="clearfix"></div>

<div class="container">

<p id="notice"><%= notice %></p>
<!-- <h1>Listing Blogs</h1> -->

    <% @blogs.each do |blog| %>
    <h2><%= link_to blog.title, blog %></h2>
    <p>By <em><%= blog.author %></em></p>
    <hr />
    <p><%=h blog.post.html_safe %></p>
    <br />
    <div class="fb-like" data-href="https://www.facebook.com/NuvolaNetworks" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
    <br /><br />
    <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
       <P> <%= link_to 'Edit', edit_blog_path(blog) %> | 
      <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %> |

    <% end %>

<%= link_to 'New Blog', new_blog_path %></P>
<% end %>
<% end %>
</div>
<div class="clearfix"></div>

<div class="copyrights">
<div class="container">
  
    <ul>
        <li><a href="http://www.facebook.com/nuvolanetworks"><i class="fa fa-facebook"></i></a></li>
        <li><a href="http://www.twitter.com/nuvolanetworks"><i class="fa fa-twitter"></i></a></li>
        <li><a href="https://plus.google.com/+RickBarkley1"><i class="fa fa-google-plus"></i></a></li>
        <li><a href="http://pintrest.com/nuvolio"><i class="fa fa-pinterest"></i></a></li>
        <li><a href="https://www.linkedin.com/company/nuvola-networks-llc"><i class="fa fa-linkedin"></i></a></li>
    </ul>
    
    <div class="clearfix"></div>
    <div class="margin_top3"></div>
    
    © Nuvola Networks. All rights reserved.

</div>
</div><!-- end copyrights section -->

<a href="#" class="scrollup">Scroll</a><!-- end scroll to top of the page-->

</div>

app/views/blogs/new.html.erb
<head>
    <!-- this styles only adds some repairs on idevices  -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Google fonts - witch you want to use - (rest you can just remove) -->
    <link href='http://fonts.googleapis.com/css?family=Montserrat+Alternates:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    
    <!--[if elt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
    
    <!-- ######### CSS STYLES ######### -->
  
    <link rel="stylesheet" href="css/reset.css" type="text/css" />
  <link rel="stylesheet" href="css/style.css" type="text/css" />
    
    <link rel="stylesheet" href="css/font-awesome/css/font-awesome.min.css">
    
    <!-- responsive devices styles -->
  <link rel="stylesheet" media="screen" href="css/responsive-leyouts.css" type="text/css" />
    
<!-- just remove the below comments witch color skin you want to use -->
    <!-- <link rel="stylesheet" href="css/colors/red.css" /> -->
    <!--<link rel="stylesheet" href="css/colors/green.css" />-->
    <!--<link rel="stylesheet" href="css/colors/cyan.css" />-->
    <link rel="stylesheet" href="css/colors/orange.css" /> 
   <!-- <link rel="stylesheet" href="css/colors/lightblue.css" /> -->
    <!--<link rel="stylesheet" href="css/colors/pink.css" />-->
    <!--<link rel="stylesheet" href="css/colors/purple.css" />-->
    <!--<link rel="stylesheet" href="css/colors/bridge.css" />-->
   <!-- <link rel="stylesheet" href="css/colors/slate.css" /> -->
    <!--<link rel="stylesheet" href="css/colors/yellow.css" />-->
    <!-- <link rel="stylesheet" href="css/colors/darkred.css" /> -->
  
  
    <!-- menu -->
    <link href="js/mainmenu/sticky.css" rel="stylesheet">
    <link rel="stylesheet" href="js/mainmenu/menu.css">
    <!-- forms -->
    <link rel="stylesheet" href="js/form/sky-forms.css" type="text/css" media="all">
    
    
</head>



<div class="site_wrapper">

<div id="header">
    
  <div id="trueHeader">
    
  <div class="wrapper">
    
     <div class="container_full">
        
        <header>
        
            <!-- Logo -->
            <div class="logo"><a href="/#home"><img src="images/logo_horz_black_back.jpg" alt="Nuvola Networks Logo" /></a></div>
            
            <!-- Menu -->
            <div class="menu_main">
            
            <nav class="nav-collapse">
                <ul>
                  <li><a href="/#home">Home</a></li>
                  <li><a href="/#about">About</a></li>
               <!--   <li><a href="#portfolio" data-scroll><i class="fa fa-circle"></i>Portfolio</a></li> -->
                  <li><a href="/#services">Services</a></li>
                  <li><a href="/#pricing">Pricing</a></li>
                  <li><a href="/#blog">Blog</a></li>
                  <li><a href="/#contact">Contact</a></li>
                </ul>
            </nav>
            
            </div><!-- end menu -->  
        
        </header>
        
     </div>
    
  </div>
    
  </div>
    
</div>
<div class="clearfix"></div>

<div class="container">
    <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

<% else %>

<h1>You are not Authorized to be here! <a href="http://www.nuvola-networks.com"> Go Back</a></h1>
<% end %>
<% end %>
</div>

<div class="clearfix"></div>

<div class="copyrights">
<div class="container">
  
    <ul>
        <li><a href="http://www.facebook.com/nuvolanetworks"><i class="fa fa-facebook"></i></a></li>
        <li><a href="http://www.twitter.com/nuvolanetworks"><i class="fa fa-twitter"></i></a></li>
        <li><a href="https://plus.google.com/+RickBarkley1"><i class="fa fa-google-plus"></i></a></li>
        <li><a href="http://pintrest.com/nuvolio"><i class="fa fa-pinterest"></i></a></li>
        <li><a href="https://www.linkedin.com/company/nuvola-networks-llc"><i class="fa fa-linkedin"></i></a></li>
    </ul>
    
    <div class="clearfix"></div>
    <div class="margin_top3"></div>
    
    © Nuvola Networks. All rights reserved.

</div>
</div><!-- end copyrights section -->

<a href="#" class="scrollup">Scroll</a><!-- end scroll to top of the page-->

</div>

app/views/blogs/show.html.erb
<head>
    <!-- this styles only adds some repairs on idevices  -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Google fonts - witch you want to use - (rest you can just remove) -->
    <link href='http://fonts.googleapis.com/css?family=Montserrat+Alternates:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    
    <!--[if elt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
    
    <!-- ######### CSS STYLES ######### -->
  
    <link rel="stylesheet" href="css/reset.css" type="text/css" />
  <link rel="stylesheet" href="css/style.css" type="text/css" />
    
    <link rel="stylesheet" href="css/font-awesome/css/font-awesome.min.css">
    
    <!-- responsive devices styles -->
  <link rel="stylesheet" media="screen" href="css/responsive-leyouts.css" type="text/css" />
    
<!-- just remove the below comments witch color skin you want to use -->
    <!-- <link rel="stylesheet" href="css/colors/red.css" /> -->
    <!--<link rel="stylesheet" href="css/colors/green.css" />-->
    <!--<link rel="stylesheet" href="css/colors/cyan.css" />-->
    <link rel="stylesheet" href="css/colors/orange.css" /> 
   <!-- <link rel="stylesheet" href="css/colors/lightblue.css" /> -->
    <!--<link rel="stylesheet" href="css/colors/pink.css" />-->
    <!--<link rel="stylesheet" href="css/colors/purple.css" />-->
    <!--<link rel="stylesheet" href="css/colors/bridge.css" />-->
   <!-- <link rel="stylesheet" href="css/colors/slate.css" /> -->
    <!--<link rel="stylesheet" href="css/colors/yellow.css" />-->
    <!-- <link rel="stylesheet" href="css/colors/darkred.css" /> -->
  
  
    <!-- menu -->
    <link href="js/mainmenu/sticky.css" rel="stylesheet">
    <link rel="stylesheet" href="js/mainmenu/menu.css">
    <!-- forms -->
    <link rel="stylesheet" href="js/form/sky-forms.css" type="text/css" media="all">
    
    
</head>



<div class="site_wrapper">

<div id="header">
    
  <div id="trueHeader">
    
  <div class="wrapper">
    
     <div class="container_full">
        
        <header>
        
            <!-- Logo -->
            <div class="logo"><a href="/#home"><img src="images/logo_horz_black_back.jpg" alt="Nuvola Networks Logo" /></a></div>
            
            <!-- Menu -->
            <div class="menu_main">
            
            <nav class="nav-collapse">
                <ul>
                  <li><a href="/#home">Home</a></li>
                  <li><a href="/#about">About</a></li>
               <!--   <li><a href="#portfolio" data-scroll><i class="fa fa-circle"></i>Portfolio</a></li> -->
                  <li><a href="/#services">Services</a></li>
                  <li><a href="/#pricing">Pricing</a></li>
                  <li><a href="/#blog">Blog</a></li>
                  <li><a href="/#contact">Contact</a></li>
                </ul>
            </nav>
            
            </div><!-- end menu -->  
        
        </header>
        
     </div>
    
  </div>
    
  </div>
    
</div>
<div class="clearfix"></div>

<div class="container">
<p id="notice"><%= notice %></p>

    <h2><%= @blog.title %></h2>
    <p>By <em><%= @blog.author %></em></p>
    <hr />
    <p><%=h @blog.post.html_safe %></p>
    <br /><br />
    <div class="fb-like" data-href="https://www.facebook.com/NuvolaNetworks" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
    <div class="fb-comments" data-href="https://www.facebook.com/NuvolaNetworks" data-numposts="5" data-colorscheme="light"></div>
    <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

<% else %>
<%= link_to 'Back to Blogs', blogs_path %> |
<%= link_to 'Back to Main Site', 'http://nuvola-networks.com' %>
<% end %>
<% end %>

</div>

<div class="clearfix"></div>

<div class="copyrights">
<div class="container">
  
    <ul>
        <li><a href="http://www.facebook.com/nuvolanetworks"><i class="fa fa-facebook"></i></a></li>
        <li><a href="http://www.twitter.com/nuvolanetworks"><i class="fa fa-twitter"></i></a></li>
        <li><a href="https://plus.google.com/+RickBarkley1"><i class="fa fa-google-plus"></i></a></li>
        <li><a href="http://pintrest.com/nuvolio"><i class="fa fa-pinterest"></i></a></li>
        <li><a href="https://www.linkedin.com/company/nuvola-networks-llc"><i class="fa fa-linkedin"></i></a></li>
    </ul>
    
    <div class="clearfix"></div>
    <div class="margin_top3"></div>
    
    © Nuvola Networks. All rights reserved.

</div>
</div><!-- end copyrights section -->

<a href="#" class="scrollup">Scroll</a><!-- end scroll to top of the page-->

</div>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if IE 7 ]>    <html lang="en-gb" class="isie ie7 oldie no-js"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en-gb" class="isie ie8 oldie no-js"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en-gb" class="isie ie9 no-js"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en-gb" class="no-js"> <!--<![endif]-->

<head>
	
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="keywords" content="" />
	<meta name="description" content="" />
    <!-- Favicon --> 
	<link rel="shortcut icon" href="images/favicon.ico">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <title>Nuvola Networks - Online Training Re-Imagined</title>
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=196998807069297&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<%= yield %>




</body>
</html>